import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import InitialMessage from "../../components/initial-message";

const GeneralLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
        />
      </Head>
      <Navbar />
      <main className="body">{children}</main>
      <InitialMessage />
    </>
  );
};

export default GeneralLayout;
